# mkdocs.yml
site_name: Hazm | Persian NLP Toolkit
site_description: A Python library for Persian language processing
site_author: Roshan
site_url: https://www.roshan-ai.ir/hazm/
repo_url: https://github.com/roshan-research/hazm

remote_branch: master
repo_name: hazm

docs_dir: documentation
site_dir: docs/docs

copyright: |

  © All rights reserved to Roshan. &nbsp;|&nbsp;
  <a href="#__consent">Change cookie settings</a>

theme:
  name: material
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  logo: assets/logo.svg
  font:
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select

plugins:
  - macros:
      module_name: mkdocs_macros
  - autorefs
  - mkdocstrings:      
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - search
  - tags
  - glightbox
  - offline

extra_css:
  - custom-style.css

nav:
  - Introduction: index.md
  - Classes and Functions:
      - Overview: content/hazm/index.md
      - Normalizer: content/hazm/normalizer.md
      - Informal Normalizer: content/hazm/informal_normalizer.md
      - Stemmer: content/hazm/stemmer.md
      - Lemmatizer: content/hazm/lemmatizer.md
      - Sentence Tokenizer: content/hazm/sentence_tokenizer.md
      - Word Tokenizer: content/hazm/word_tokenizer.md
      - Embedding: content/hazm/embedding.md
      - Sequence Tagger: content/hazm/sequence_tagger.md
      - Token Splitter: content/hazm/token_splitter.md
      - Chunker: content/hazm/chunker.md
      - POS Tagger: content/hazm/pos_tagger.md
      - Dependency Parser: content/hazm/dependency_parser.md
      - Utils: content/utils.md
      - Corpus Readers:
          - Overview: content/hazm/corpus_readers/index.md
          - MirasText Reader: content/hazm/corpus_readers/mirastext_reader.md
          - Bijankhan Reader: content/hazm/corpus_readers/bijankhan_reader.md
          - Dadegan Reader: content/hazm/corpus_readers/dadegan_reader.md
          - Universal Dadegan Reader: content/hazm/corpus_readers/universal_dadegan_reader.md
          - Degarbayan Reader: content/hazm/corpus_readers/degarbayan_reader.md
          - Hamshahri Reader: content/hazm/corpus_readers/hamshahri_reader.md
          - Persica Reader: content/hazm/corpus_readers/persica_reader.md
          - Persian Plain Text Reader: content/hazm/corpus_readers/persian_plain_text_reader.md
          - Peykare Reader: content/hazm/corpus_readers/peykare_reader.md
          - Quran Reader: content/hazm/corpus_readers/quran_reader.md
          - SentiPers Reader: content/hazm/corpus_readers/sentipers_reader.md
          - TNews Reader: content/hazm/corpus_readers/tnews_reader.md
          - Treebank Reader: content/hazm/corpus_readers/treebank_reader.md
          - Verb Valency Reader: content/hazm/corpus_readers/verbvalency_reader.md
          - Wikipedia Reader: content/hazm/corpus_readers/wikipedia_reader.md
          - Mizan Reader: content/hazm/corpus_readers/mizan_reader.md
          - NER Reader: content/hazm/corpus_readers/ner_reader.md
          - Naab Reader: content/hazm/corpus_readers/naab_reader.md
          - Arman Reader: content/hazm/corpus_readers/arman_reader.md
          - FaSpell Reader: content/hazm/corpus_readers/faspell_reader.md
          - PN Summary Reader: content/hazm/corpus_readers/pn_summary_reader.md

  - Other Sections:
      - Hazm in Other Languages: content/in-other-languages.md

extra:
  repo_url: https://github.com/roshan-research/hazm
  consent:
    title: Cookie Consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/roshan-research

extra_javascript:
  - https://unpkg.com/mermaid@9.1.5/dist/mermaid.min.js

markdown_extensions:
  - markdown.extensions.abbr
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.md_in_html
  - markdown.extensions.toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.b64
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.striphtml
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.arithmatex

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
