name: Build docs
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
        
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Configure Poetry to use Python 3.12
        run: poetry env use python3.12
          
      - name: Install requirements
        run: |
          poetry lock
          poetry install --with docs

      - name: Build docs
        run: mkdocs build --clean

      - name: Push back changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "update docs"
          commit_user_name: "documentation-bot"
          commit_user_email: "documentation-bot@users.noreply.github.com"
