name: Close old issues that need reply

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Close old issues that need reply
        uses: imhoffd/needs-reply@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-close: 14
          close-message: |
            This issue has been automatically closed because there hasn't been a reply in 2 weeks.
          issue-label: needs-reply